name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: windows-latest }
          - { os: macOS-latest }
          - { os: ubuntu-latest }

    runs-on: ${{ matrix.config.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        global-json-file: src/dotnet-counters-ui/global.json

    - name: Configure Linux
      if: runner.os == 'Linux'
      run: apt-get install -y libgdiplus

    - name: Configure MacOS
      if: runner.os == 'MacOS'
      run: brew install mono-libgdiplus

    - name: Restore dependencies
      run: dotnet restore --verbosity minimal src/dotnet-counters-ui

    - name: Build
      run: dotnet build --no-restore --configuration Release src/dotnet-counters-ui

    # No tests - no problems! TODO: Enable when there are tests (if any)
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal --configuration Release src
